---
title: "Challenge 2"
author: "Adam Kong"
format:
  html:
    self-contained: true
    code-tools: true
    code-fold: true
execute:
  echo: true
  error: true
---

```{r setup}
#| message: FALSE
library(tidyverse)
library(here)
library(ggridges)
```

```{r data}
#| message: FALSE
# Code for question 1! 
surveys <- read_csv(here::here("Week 2", "Lab 2", "surveys.csv"))
```

### **MEDIUM - RIDGE PLOTS**


```{r}
# USING CODE FROM QUESTION 13 
ggplot(data = surveys) +
  geom_density_ridges(mapping = aes(x = weight, y = genus, 
                                    fill = genus,)) +
  xlab("Weight (g)") +
  ylab("Genus")

# Use species to fill in the density curve since it helps visualize the dataset.

```
If we use geom_density(mapping = aes(x = weight, y = species)) it will graph incorrectly where there is no density but and just ridges
```{r}
ggplot(data = surveys) +
  geom_density(mapping = aes(x = weight, y = genus, fill = genus))
```

### **SPICY - EXPLORING COLOR THEMES**

```{r}
colors_ex <- c("blue", "black", "red", "green", "orange", "yellow", "turquoise", "grey", "brown", "pink", "tan", "#0072B2", "#D55E00", "#CC79A7")

c_genus <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
                      "#0072B2", "#D55E00", "#CC79A7", "#000000", "#E69F00",
                      "#56B4E9", "#009E73", "#F0E442", 
                      "#0072B2", "#D55E00", "#CC79A7")

graph1 <- ggplot(data = surveys, aes(x = weight, 
                                     y = species, color = genus)) +
  scale_color_manual(values = colors_ex) +
  geom_boxplot() +
  labs(
    title = "Weight and Hindfoot Length Random Colors",
    x = "Weight (g)",
    y = "Species"
  )
graph1


graph2 <- ggplot(data = surveys, aes(x = weight, 
                                     y = species, color = genus)) +
  scale_color_manual(values = c_genus) +
  geom_boxplot() +
  labs(
    title = "Weight and Hindfoot Length Genus Color Scheme",
    x = "Weight (g)",
    y = "Species"
  )
graph2
```

### **HOT - EXPLORING GGPLOT2 ANNOTATION**

```{r}
# http://www.sthda.com/english/wiki/ggplot2-rotate-a-graph-reverse-and-flip-the-plot
```
```{r}
c_genus <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
                      "#0072B2", "#D55E00", "#CC79A7", "#000000", "#E69F00",
                      "#56B4E9", "#009E73", "#F0E442", 
                      "#0072B2", "#D55E00", "#CC79A7")

annotate_graph <- ggplot(data = surveys, aes(x = weight, 
                                     y = species, color = genus)) +
  scale_color_manual(values = c_genus) +
  geom_boxplot() +
  theme(legend.position = "none") +
  annotate("text", y = 1, x = 350, label = "Neotoma") +
  annotate("text", y = 6, x = 300, label = "Sigmodon") +
  annotate("text", y = 10, x = 200, label = "Test genus")
  labs(
    title = "Weight and Hindfoot Length Genus Color Scheme",
    x = "Weight (g)",
    y = "Hindfoot Length (mm)"
  ) +
  theme_dark()
annotate_graph
```

# Challenge 2 Submission

Once you have completed your lab you should upload **both** your rendered HTML file and your Quarto file to Canvas.