---
title: "Practice Activity 9.2 Regression"
author: "Adam Kong"
format: 
  html:
    self-contained: true
    code-tools: true
    code-fold: true
execute:
  echo: true
  error: true
---

**Practice Activity 9.2: Simulation**

Trombones Normal Distribution mean = 4.6, sd = 0.8

Trumpets Uniform Distribution between 1.5 and 3.5

Reed Chi-Squared 4 degrees of freedom

```{r}
# Trumpet
qunif(0.95, min = 1.5, max = 3.5)
# Trombone
qnorm(0.10, mean = 4.6, sd = 0.8)
1 - pnorm(5, mean = 4.6, sd = 0.8)
tromboneNum <- rnorm(100, mean = 4.6, sd = 0.8)

sum(tromboneNum < 4)

# Reed
1 - pchisq(5, df = 4)
```

Wells Fargo Shipment 1957

To: Harold Hill, Mason City, Iowa From: Music Factory, Gary, Indiana

Items included: Trombones: 76 Cornets: 110 Saxophones: 542 Clarinets: 318 Bassoons: 175

Total Shipped Weight: 4532 lbs.

```{r}
set.seed(1957)

music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)
  
  return(sum(trombones, cornets, reeds))
  
}

my_weights <- map_dbl(.x = 1:1000, 
                      .f = ~ music_man(n_tromb = 76, 
                                       n_cor = 110, 
                                       n_reed = 542 + 318 + 175)
                      ) 
```

```{r}
hist(my_weights)
sum(my_weights < 4532)
```
