---
title: "Practice Activity 9.2"
author: "Adam Kong"
format: 
  html:
    self-contained: true
    code-tools: true
    code-fold: true
execute:
  echo: true
  error: true
---

## Practice Activity 9.2

```{r}
library(tidyverse)
```

```{r}
library(palmerpenguins)

penguins %>%
  ggplot(aes(x = bill_depth_mm, y = bill_length_mm)) +
  geom_point() +
  stat_smooth(method = "lm") + 
  labs(x = "Bill Depth (mm)", 
       y = "Bill Length (mm)")
```

```{r}
my_model <- penguins |>
  lm(bill_length_mm ~ bill_depth_mm, data = _)
```

```{r}
my_model
```

```{r}
summary(my_model)
```

```{r}
broom::tidy(my_model) 
```

```{r}
broom::glance(my_model)
```

```{r}
my_model_2 <- penguins |>
  lm(bill_length_mm ~ bill_depth_mm*species, data = _)
```

```{r}
my_model_2
```

```{r}
broom::glance(my_model_2)
```

```{r}
library(palmerpenguins)

penguins %>%
  ggplot(aes(x = bill_depth_mm, y = bill_length_mm, color=species)) +
  geom_point() +
  stat_smooth(method = "lm") + 
  labs(x = "Bill Depth (mm)", 
       y = "Bill Length (mm)")
```

```{r}
summary(my_model_2)
```

```{r}
broom::tidy(my_model_2)
```
